### ISSUE TITLE
training with preprocessed data failed

### ISSUE THREAD

**Issue by Alen-Wong** [raja-kumar/depth-aware-3DGS#3]
Thank you for this excellent work, I encountered the following error when training with preprocessed data, how can I resolve it?
```
Optimizing 
Output folder: ./output/3765832a-c
Reading camera 8/8
Loading Training Cameras
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1
Loading Test Cameras
Number of points at initialisation :  2108
Training progress:   6%|▊            | 600/10000 [01:10<17:07,  9.15it/s, Loss=0.2673802]Traceback (most recent call last):
  File "train.py", line 322, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 223, in training
    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold)
  File "/media/data_nix/wangzihao/code/depth-aware-3DGS/scene/gaussian_model.py", line 393, in densify_and_prune
    self.densify_and_clone(grads, max_grad, extent)
  File "/media/data_nix/wangzihao/code/depth-aware-3DGS/scene/gaussian_model.py", line 384, in densify_and_clone
    new_scaling = self._scaling[selected_pts_mask]
IndexError: The shape of the mask [2108] at index 0 does not match the shape of the indexed tensor [1, 3] at index 0
Training progress:   6%|▊            | 600/10000 [01:10<18:18,  8.56it/s, Loss=0.2673802]
```

**Comment by YoungXusheng** [comment]
The calculation of dist2 was wrong,u can check the gaussian_module

**Comment by JX-Github-web** [comment]
Hi, have you solved this problem? I'm getting the same error as well

**Comment by YoungXusheng** [comment]
您好，我是勇旭升。谢谢您的邮件，我已经收到了。

**Comment by JX-Github-web** [comment]
![image](https://github.com/user-attachments/assets/06e3695e-cf9b-415d-9865-95b6375cecc1)

**Comment by duyanxi** [comment]
same error here. have you sloved this promblem?

**Comment by YoungXusheng** [comment]
您好，我是勇旭升。谢谢您的邮件，我已经收到了。

**Comment by liushuishui7** [comment]
Have you solved this problem? I had the same problem。

**Comment by liushuishui7** [comment]
python train.py -s ./data/fern --scene fern
Optimizing&nbsp;
Output folder: ./output/647b96f1-4 [17/04 02:51:52]
Tensorboard not available: not logging progress [17/04 02:51:52]
Checking scene type in path: /data/lmb/depth-aware-3DGS/data/fern [17/04 02:51:52]
Subdirectories found: ['database.db', 'sparse', 'images_low_res', 'depth', '.DS_Store', 'images', 'abs_depth'] [17/04 02:51:52]
Reading camera 8/8 [17/04 02:51:52]
Loading Training Cameras [17/04 02:51:52]
[ INFO ] Encountered quite large input images (&gt;1.6K pixels width), rescaling to 1.6K.
&nbsp;If this is not desired, please explicitly specify '--resolution/-r' as 1 [17/04 02:51:52]
Loading Test Cameras [17/04 02:51:57]
Number of points at initialisation :&nbsp; 2108 [17/04 02:51:57]
Training progress:&nbsp; &nbsp;6%|███▌&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 600/10000 [01:14<18:29,&nbsp; 8.48it/s, Loss=0.2663194]Traceback (most recent call last):
&nbsp; File "/data/lmb/depth-aware-3DGS/train.py", line 326, in <module&gt;
&nbsp; &nbsp; training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
&nbsp; File "/data/lmb/depth-aware-3DGS/train.py", line 225, in training
&nbsp; &nbsp; gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold)
&nbsp; File "/data/lmb/depth-aware-3DGS/scene/gaussian_model.py", line 396, in densify_and_prune
&nbsp; &nbsp; self.densify_and_clone(grads, max_grad, extent)
&nbsp; File "/data/lmb/depth-aware-3DGS/scene/gaussian_model.py", line 387, in densify_and_clone
&nbsp; &nbsp; new_scaling = self._scaling[selected_pts_mask]
IndexError: The shape of the mask [2108] at index 0 does not match the shape of the indexed tensor [1, 3] at index 0
Training progress:&nbsp; &nbsp;6%|███▌&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 600/10000 [01:14<19:30,&nbsp; 8.03it/s, Loss=0.2663194]

您好我在复现您的论文代码时，遇到了这个问题，向您请教如何处理解决





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "raja-kumar/depth-aware-3DGS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年4月15日(星期二) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [raja-kumar/depth-aware-3DGS] training with preprocessed data failed (Issue #3)



   您好，我是勇旭升。谢谢您的邮件，我已经收到了。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  YoungXusheng left a comment (raja-kumar/depth-aware-3DGS#3)
 您好，我是勇旭升。谢谢您的邮件，我已经收到了。

**Comment by raja-kumar** [comment]
@liushuishui7 The diff-gaussian-rasterization module is not linked correctly. can you please install the diff-gaussian-rasterization from this repo https://github.com/ashawkey/diff-gaussian-rasterization and try again

**Comment by liushuishui7** [comment]
I have tried your solution, but this problem still occurs.
The length of selected_pts_mask is inconsistent with the current number of Gaussian points, which may be caused by logical errors in the gradient calculation or pruning steps?

(depth_aware_3dgs) ***@***.***:/data/lmb/depth-aware-3DGS$ python train.py -s ./data/fern --scene fern
Optimizing&nbsp;
Output folder: ./output/1e3fa6bc-8 [19/04 21:29:05]
Tensorboard not available: not logging progress [19/04 21:29:05]
Checking scene type in path: /data/lmb/depth-aware-3DGS/data/fern [19/04 21:29:05]
Subdirectories found: ['database.db', 'sparse', 'images_low_res', 'depth', '.DS_Store', 'images', 'abs_depth'] [19/04 21:29:05]
Reading camera 8/8 [19/04 21:29:06]
Loading Training Cameras [19/04 21:29:06]
[ INFO ] Encountered quite large input images (&gt;1.6K pixels width), rescaling to 1.6K.
&nbsp;If this is not desired, please explicitly specify '--resolution/-r' as 1 [19/04 21:29:06]
Loading Test Cameras [19/04 21:29:11]
Number of points at initialisation :&nbsp; 2108 [19/04 21:29:11]
Training progress:&nbsp; &nbsp;6%|███▌&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 600/10000 [01:14<18:38,&nbsp; 8.40it/s, Loss=0.2659831]Traceback (most recent call last):
&nbsp; File "/data/lmb/depth-aware-3DGS/train.py", line 326, in <module&gt;
&nbsp; &nbsp; training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
&nbsp; File "/data/lmb/depth-aware-3DGS/train.py", line 225, in training
&nbsp; &nbsp; gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold)
&nbsp; File "/data/lmb/depth-aware-3DGS/scene/gaussian_model.py", line 396, in densify_and_prune
&nbsp; &nbsp; self.densify_and_clone(grads, max_grad, extent)
&nbsp; File "/data/lmb/depth-aware-3DGS/scene/gaussian_model.py", line 387, in densify_and_clone
&nbsp; &nbsp; new_scaling = self._scaling[selected_pts_mask]
IndexError: The shape of the mask [2108] at index 0 does not match the shape of the indexed tensor [1, 3] at index 0
Training progress:&nbsp; &nbsp;6%|███▌&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 600/10000 [01:14<19:23,&nbsp; 8.08it/s, Loss=0.2659831]





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "raja-kumar/depth-aware-3DGS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年4月20日(星期天) 上午7:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [raja-kumar/depth-aware-3DGS] training with preprocessed data failed (Issue #3)



   
@liushuishui7 The diff-gaussian-rasterization module is not linked correctly. can you please install the diff-gaussian-rasterization from this repo https://github.com/ashawkey/diff-gaussian-rasterization and try again

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  raja-kumar left a comment (raja-kumar/depth-aware-3DGS#3)
 
@liushuishui7 The diff-gaussian-rasterization module is not linked correctly. can you please install the diff-gaussian-rasterization from this repo https://github.com/ashawkey/diff-gaussian-rasterization and try again

**Comment by knight-joker** [comment]
I also have this problem ,and spend too much time but filed to solve it

**Comment by knight-joker** [comment]
Optimizing
Output folder: ./output/c93aaa39-1 [15/04 16:10:13]
Tensorboard not available: not logging progress [15/04 16:10:13]
Reading camera 8/8 [15/04 16:10:13]
Loading Training Cameras [15/04 16:10:13]
Loading Test Cameras [15/04 16:10:14]
Number of points at initialisation :  2108 [15/04 16:10:14]
Training progress:   0%|                                                                                    | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\3Drebuild\depth-aware-3DGS\depth-aware-3DGS\train.py", line 364, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "C:\Users\lenovo\Desktop\3Drebuild\depth-aware-3DGS\depth-aware-3DGS\train.py", line 114, in training
    assert gaussians._scaling.shape[0] == n_pts, \
AssertionError: [FATAL] _scaling shape mismatch: 1 vs xyz 2108. Check prune/densify logic.
Training progress:   0%|                                                                                    | 0/10000 [00:00<?, ?it/s]

**Comment by knight-joker** [comment]
I give up this
