### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by JX-Github-web** [raja-kumar/depth-aware-3DGS#4]
Traceback (most recent call last):
  File "/root/autodl-tmp/depth-aware-3DGS/train.py", line 322, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/root/autodl-tmp/depth-aware-3DGS/train.py", line 101, in training
    loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image))
  File "/root/autodl-tmp/depth-aware-3DGS/utils/loss_utils.py", line 38, in ssim
    window = window.cuda(img1.get_device())
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   5%|███████▎                                                                                                                                                | 480/10000 [00:54<17:54,  8.86it/s, Loss=0.3098132]
(depth_aware_3dgs) root@autodl-container-1ca84e8b33-f925896c:~/autodl-tmp/depth-aware-3DGS# 

![image](https://github.com/user-attachments/assets/274f505e-2ad4-488f-852e-d8331dfa8b84)

I used a 32G gpu, but out of memory

**Comment by Grizemc** [comment]
maybe you can improve the version of the  cudatookit
